name=input("Enter your name:")
branch=input("Tell me your branch:")
gender=input("What is your Gender:")
CollegeName=input("What's your College Name:")
age=int(input("Enter your age:"))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",CollegeName)
print("Age:",age)
